export const authStrings = {
  linkBack: 'Voltar para o início',
  nameLabel: 'Nome Completo',
  namePlaceholder: 'Digite seu nome completo',
  emailLabel: 'E-mail',
  emailPlaceholder: 'Digite seu e-mail',
  passwordLabel: 'Senha',
  passwordPlaceholder: 'Digite sua senha',
  confirmPasswordLabel: 'Confirmação da senha',
  confirmPasswordPlaceholder: 'Confirme sua senha',
  mainText: 'Entre ou cadastre-se',
  secondaryText: 'Para entrar na plataforma é necessário entrar \n ou criar uma conta.',
  linkForgotPassword: 'Esqueceu a senha?',
  confirmTerms: 'Li e concordo com os',
  linkTerms: 'Termos de uso',
  linkPolicy: 'Política de privacidade',
  login: 'Faça login',
  register: 'Cadastre-se',
  successRegister: 'Cadastro realizado com sucesso!',
  haveAnAccount: 'Já possui uma conta?',
  loading: 'Carregando',
  button: {
    login: 'Login',
    register: 'Registrar',
  },
};
